### ISSUE TITLE
add tags <meta>

### ISSUE THREAD

**Issue by dozyktz** [dozyktz/dozyktz.github.io#8]
### who:
- me as owner
### what:
- [x] add Meta Tag name="author"
- [x] add Meta Tag name="description"
- [x] add Meta Tag name="keywords"
### why:
- to describe a page content
